// Exports to C#
EXTERNAL DoGoOutside()
EXTERNAL DoGoToBed()
EXTERNAL TryPurchase(item)
EXTERNAL GetEvent(event)
EXTERNAL GetCost(cost)
EXTERNAL SetEvent(event, val)
EXTERNAL GainResource(resource, amount)
EXTERNAL DoReturnToRover()
EXTERNAL DoGoBackToHab()