// Exports to C#
EXTERNAL DoGoOutside()
EXTERNAL DoGoToBed()
EXTERNAL DoPurchase(item)
EXTERNAL GetEvent(event)
EXTERNAL GetCost(cost)
EXTERNAL GetTodayIsSafe()
EXTERNAL GetIsBedtime()
EXTERNAL SetEvent(event, val)
EXTERNAL GainResource(resource, amount)
EXTERNAL DoReturnToRover()
EXTERNAL DoGoBackToHab()
EXTERNAL HasBuildProject()
EXTERNAL GetToWork()
EXTERNAL AdvanceTime(hours)
EXTERNAL CanPurchase(item)
EXTERNAL GetDeathText()
EXTERNAL DoRestartGame()